---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action 🧪'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
    timeout-minutes: 3
    steps:
      - name: 'Checkout repository'
        # yamllint disable rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Running action: ${{ github.repository }}"
        uses: ./
        with:
          licenses: |-
            Apache-2.0

      - name: "Running action: ${{ github.repository }}"
        uses: ./
        with:
          debug: true
          licenses: |-
            Apache-2.0

      # Test against the lftools repository
      - name: 'Checkout lftools repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: 'lfit/releng-lftools'
          path: 'lftools'

      - name: "Running action: ${{ github.repository }}"
        uses: ./
        with:
          path: 'lftools/lftools'
          licenses: |-
            Apache-2.0
